import React, { Component } from 'react'

export default class Information extends Component {
    renderTestInfo() {

        if (this.props.selectedComponent === "client")
            return this.renderClientInfo()

        else if (this.props.selectedComponent === "both")
            return this.renderClientServerInfo()
    }

    renderClientInfo() {
        return (
            <div className="col">
                <p>In order to successufully test a Client component:</p>
                <ul>
                    <li>We assume that the Client being tested will try to communicate with a server already running somewhere on Internet. </li>
                    <li>The Client project has to be written in Java.</li>
                    <li>The project has to be a NetBeans IDE project.</li>
                    <li>The project must contain the build directory (usually found at the root directory) that is generated by the NetBeans IDE when it is compiled.</li>
                    <li>If testing a single project, the zip file being uploaded must contain the project directory.</li>
                    <li>If testing multiple projects, the zip file being uploaded must contain zip files of each project.</li>
                    <li>If testing multiple projects, we assume that the class with the main method and its package names are the same for each project.</li>
                    <li>The system takes about 10 seconds to test a single project.</li>
                </ul>
            </div>
        )
    }

    renderClientServerInfo() {
        return (
            <div className="col">
                <p>In order to successufully test both Client and Server components:</p>
                <ul>
                    <li>We assume that both Client and Server components will try to communicate to each other.</li>
                    <li>Both Client and Server have to be written in Java.</li>
                    <li>Both Client and Server have to be in separate project.</li>
                    <li>Each project has to be a NetBeans IDE project.</li>
                    <li>The Server component must be a SOAP web service.</li>
                    <li>The Client project must contain the build directory (usually found at the root directory) that is generated by the NetBeans IDE when it is compiled.</li>
                    <li>If testing a single project with both Client and Server components, the zip file being uploaded must contain the project directories of each components.</li>
                    <li>If testing multiple projects with both Client and Server components, the zip file being uploaded must contain zip files of each project containing the project directories of each components.</li>
                    <li>If testing multiple projects, we assume that the class with the main method and its package names are the same for each project.</li>
                    <li>The system takes about 30 seconds to test a single project.</li>
                </ul>
            </div>
        )
    }

    render() {
        return (
            <div className="container">
                <div className="row">
                    <div className="col-lg-6"><h4>Before testing</h4><hr className="myhr" /></div>
                </div>
                <div className="row bottomspace">
                    {this.renderTestInfo()}
                </div>
            </div>
        )
    }
} 